extend-include = ["*.ipynb"]

[format]
exclude = ["*.ipynb"]

[lint]
select = [
   "D", "D213"
]
ignore = ["D102", "D105", "D107", "D212"]

[lint.pydocstyle]
# Use pep257 docstrings.
convention = "google"
